### ISSUE TITLE
check is not defined

### ISSUE THREAD

**Issue by dmitrijs-balcers** [maximummeteor/computed-fields#3]
Hello, first I want to thank you for this package. It's awesome.

Today I tried to hook it up to my project, but unfortunately I received the following error, do you have any idea what might be the cause?

```
[ 'ReferenceError: check is not defined', 
  '    at ComputedFields.add (packages/maximum:computed-fields/lib/computed-fields.coffee:4:5)', 
```

**Comment by maxnowack** [comment]
Thank you! :)
I forgot to specify the `check` package as a dependency.
The new version is now on atmosphere.

**Comment by dmitrijs-balcers** [comment]
Wow, that was quick :+1:  Thanks
