### ISSUE TITLE
double execution on aldeed:collection2 for compute dependency

### ISSUE THREAD

**Issue by markshust** [maximummeteor/computed-fields#5]
I have the following defined as a field (using aldeed:collection2 format).

```

  num_items_inventoried: {
    type: Number,
    label: 'Number of Items Inventoried',
    defaultValue: 0,
    compute: {
      dependency: {
        collection: item_to_section,
        findId: function(itemToSectionData) {
          return itemToSectionData.section_id;
        },
        update: function(sectionData, itemToSectionData) {
          console.log(itemToSectionData);
        }
      }
    }
  },
```

The 'update' function is firing twice on an update. It should only be executing once.

**Comment by markshust** [comment]
Ok, I found the `updateOnPrevious` option and set it to `false`, and it seems the issue is resolved.

I find the default setting of `true` to be really awkward. I find it natural to assume that `update` would only be called once (this one through me for a loop for a while).

**Comment by cheesington** [comment]
Thanks for sharing your solution, that one got me too.  :+1:

**Comment by maxnowack** [comment]
I'm thinking about a complete rewrite of this package to refactor the code to es6, deprecating the atmosphere package and release a new package to npm. I'll change this behavior in the new version.

**Comment by markshust** [comment]
@maxnowack awesome, neato! :) I'll go ahead and close out this ticket.
